kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rook-ceph-rook-flexvolume-reconciler
subjects:
- kind: User
  name: system:serviceaccount:rook-ceph:rook-flexvolume-reconciler
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: rook-flexvolume-reconciler
  apiGroup: rbac.authorization.k8s.io
