kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rook-ceph-rook-flexvolume-reconciler-volumes-manager
  namespace: rook-ceph
subjects:
- kind: User
  name: system:serviceaccount:rook-ceph:rook-flexvolume-reconciler
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: rook-ceph-rook-flexvolume-reconciler-volumes-manager
  apiGroup: rbac.authorization.k8s.io
