[[constraint]]
  name = "k8s.io/api"
  #branch = "release-1.14"
  version = "kubernetes-1.14.1"

[[constraint]]
  name = "k8s.io/apimachinery"
  #branch = "release-1.14"
  version = "kubernetes-1.14.1"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.14.9"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "1.14.9"

[[constraint]]
  name = "github.com/rook/rook"
  version = "v1.2.2"

#[[constraint]]
#  name = "k8s.io/apiextensions-apiserver"
#  branch = "kubernetes-1.14.9"
